name: PR title commitlint

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    lint_pr_title:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - uses: ./.github/actions/prepare-npm-job

            - name: Lint PR title
              run: |
                  echo "${{ github.event.pull_request.title }}" | npx commitlint
